triggers:
  - description: null
    envs: []
    last_enabled_at: 2025-12-08 21:12:03.116052
    name: streamlit_trigger
    pipeline_uuid: cluster_training_pipeline
    schedule_interval: null
    schedule_type: api
    settings: null
    sla: null
    start_time: 2025-12-08 21:11:00
    status: active
    token: 189557234d5e431a972f6d0926b719e9
    variables: {}
